%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-mir-dwb-critics
Version:        1.1.1
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS mir_dwb_critics package

License:        BSD
URL:            https://github.com/dfki-ric/mir_dwb_critics
Source0:        %{name}-%{version}.tar.gz

Requires:       python3-matplotlib
Requires:       ros-noetic-angles
Requires:       ros-noetic-costmap-queue
Requires:       ros-noetic-dwb-critics
Requires:       ros-noetic-dwb-local-planner
Requires:       ros-noetic-geometry-msgs
Requires:       ros-noetic-nav-2d-msgs
Requires:       ros-noetic-nav-2d-utils
Requires:       ros-noetic-nav-core2
Requires:       ros-noetic-nav-grid-iterators
Requires:       ros-noetic-pluginlib
Requires:       ros-noetic-roscpp
Requires:       ros-noetic-sensor-msgs
BuildRequires:  ros-noetic-angles
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-costmap-queue
BuildRequires:  ros-noetic-dwb-critics
BuildRequires:  ros-noetic-dwb-local-planner
BuildRequires:  ros-noetic-geometry-msgs
BuildRequires:  ros-noetic-nav-2d-msgs
BuildRequires:  ros-noetic-nav-2d-utils
BuildRequires:  ros-noetic-nav-core2
BuildRequires:  ros-noetic-nav-grid-iterators
BuildRequires:  ros-noetic-pluginlib
BuildRequires:  ros-noetic-roscpp
BuildRequires:  ros-noetic-sensor-msgs
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
Trajectory critics for the dwb_local_planner that work well together with the
SBPL global planner on the MiR robot

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Thu Feb 11 2021 Martin Günther <martin.guenther@dfki.de> - 1.1.1-1
- Autogenerated by Bloom

* Tue Jun 30 2020 Martin Günther <martin.guenther@dfki.de> - 1.1.0-1
- Autogenerated by Bloom

