%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-mir-driver
Version:        1.1.3
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS mir_driver package

License:        BSD
URL:            https://github.com/dfki-ric/mir_robot
Source0:        %{name}-%{version}.tar.gz

Requires:       python3-websocket-client
Requires:       ros-noetic-actionlib-msgs
Requires:       ros-noetic-diagnostic-msgs
Requires:       ros-noetic-dynamic-reconfigure
Requires:       ros-noetic-geometry-msgs
Requires:       ros-noetic-mir-actions
Requires:       ros-noetic-mir-description
Requires:       ros-noetic-mir-msgs
Requires:       ros-noetic-move-base-msgs
Requires:       ros-noetic-nav-msgs
Requires:       ros-noetic-robot-state-publisher
Requires:       ros-noetic-rosgraph-msgs
Requires:       ros-noetic-rospy
Requires:       ros-noetic-rospy-message-converter
Requires:       ros-noetic-sensor-msgs
Requires:       ros-noetic-std-msgs
Requires:       ros-noetic-tf
Requires:       ros-noetic-visualization-msgs
BuildRequires:  python3-websocket-client
BuildRequires:  ros-noetic-actionlib-msgs
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-diagnostic-msgs
BuildRequires:  ros-noetic-dynamic-reconfigure
BuildRequires:  ros-noetic-geometry-msgs
BuildRequires:  ros-noetic-mir-actions
BuildRequires:  ros-noetic-mir-msgs
BuildRequires:  ros-noetic-move-base-msgs
BuildRequires:  ros-noetic-nav-msgs
BuildRequires:  ros-noetic-rosgraph-msgs
BuildRequires:  ros-noetic-roslaunch
BuildRequires:  ros-noetic-rospy
BuildRequires:  ros-noetic-rospy-message-converter
BuildRequires:  ros-noetic-sensor-msgs
BuildRequires:  ros-noetic-std-msgs
BuildRequires:  ros-noetic-tf
BuildRequires:  ros-noetic-visualization-msgs
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
A reverse ROS bridge for the MiR100 robot

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Fri Jun 11 2021 Martin Günther <martin.guenther@dfki.de> - 1.1.3-1
- Autogenerated by Bloom

* Wed May 12 2021 Martin Günther <martin.guenther@dfki.de> - 1.1.2-1
- Autogenerated by Bloom

* Thu Feb 11 2021 Martin Günther <martin.guenther@dfki.de> - 1.1.1-1
- Autogenerated by Bloom

* Tue Jun 30 2020 Martin Günther <martin.guenther@dfki.de> - 1.1.0-1
- Autogenerated by Bloom

