%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-mir-navigation
Version:        1.1.2
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS mir_navigation package

License:        BSD
URL:            https://github.com/dfki-ric/mir_robot
Source0:        %{name}-%{version}.tar.gz

Requires:       python3-matplotlib
Requires:       ros-noetic-amcl
Requires:       ros-noetic-base-local-planner
Requires:       ros-noetic-dwa-local-planner
Requires:       ros-noetic-dwb-critics
Requires:       ros-noetic-dwb-local-planner
Requires:       ros-noetic-dwb-plugins
Requires:       ros-noetic-hector-mapping
Requires:       ros-noetic-map-server
Requires:       ros-noetic-mir-driver
Requires:       ros-noetic-mir-dwb-critics
Requires:       ros-noetic-mir-gazebo
Requires:       ros-noetic-move-base
Requires:       ros-noetic-nav-core-adapter
Requires:       ros-noetic-sbpl-lattice-planner
Requires:       ros-noetic-teb-local-planner
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-roslaunch
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
Launch and configuration files for move_base, localization etc. on the MiR
robot.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Wed May 12 2021 Martin Günther <martin.guenther@dfki.de> - 1.1.2-1
- Autogenerated by Bloom

* Thu Feb 11 2021 Martin Günther <martin.guenther@dfki.de> - 1.1.1-1
- Autogenerated by Bloom

* Tue Jun 30 2020 Martin Günther <martin.guenther@dfki.de> - 1.1.0-1
- Autogenerated by Bloom

