Name:           ros-indigo-mir-driver
Version:        1.0.3
Release:        0%{?dist}
Summary:        ROS mir_driver package

Group:          Development/Libraries
License:        BSD
URL:            https://github.com/dfki-ric/mir_robot
Source0:        %{name}-%{version}.tar.gz

Requires:       python-websocket-client
Requires:       ros-indigo-actionlib-msgs
Requires:       ros-indigo-diagnostic-msgs
Requires:       ros-indigo-dynamic-reconfigure
Requires:       ros-indigo-geometry-msgs
Requires:       ros-indigo-mir-actions
Requires:       ros-indigo-mir-description
Requires:       ros-indigo-mir-msgs
Requires:       ros-indigo-move-base-msgs
Requires:       ros-indigo-nav-msgs
Requires:       ros-indigo-robot-state-publisher
Requires:       ros-indigo-rosgraph-msgs
Requires:       ros-indigo-rospy
Requires:       ros-indigo-rospy-message-converter
Requires:       ros-indigo-sensor-msgs
Requires:       ros-indigo-std-msgs
Requires:       ros-indigo-tf
Requires:       ros-indigo-visualization-msgs
BuildRequires:  python-websocket-client
BuildRequires:  ros-indigo-actionlib-msgs
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-diagnostic-msgs
BuildRequires:  ros-indigo-dynamic-reconfigure
BuildRequires:  ros-indigo-geometry-msgs
BuildRequires:  ros-indigo-mir-actions
BuildRequires:  ros-indigo-mir-msgs
BuildRequires:  ros-indigo-move-base-msgs
BuildRequires:  ros-indigo-nav-msgs
BuildRequires:  ros-indigo-rosgraph-msgs
BuildRequires:  ros-indigo-roslaunch
BuildRequires:  ros-indigo-rospy
BuildRequires:  ros-indigo-rospy-message-converter
BuildRequires:  ros-indigo-sensor-msgs
BuildRequires:  ros-indigo-std-msgs
BuildRequires:  ros-indigo-tf
BuildRequires:  ros-indigo-visualization-msgs

%description
A reverse ROS bridge for the MiR100 robot

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Mon Mar 04 2019 Martin Günther <martin.guenther@dfki.de> - 1.0.3-0
- Autogenerated by Bloom

* Mon Jul 30 2018 Martin Günther <martin.guenther@dfki.de> - 1.0.2-0
- Autogenerated by Bloom

* Tue Jul 17 2018 Martin Günther <martin.guenther@dfki.de> - 1.0.1-0
- Autogenerated by Bloom

